### ISSUE TITLE
Question on Performance

### ISSUE THREAD

**Issue by abdu292** [thecodewrapper/CH.CleanArchitecture#3]
Thanks for your effort on this.

Do you see any noticeable performance degradation by separating domain & persistence models on your projects so far?

Is everything natural when fetching large/(even small) number of items etc?

Thanks!

**Comment by thecodewrapper** [comment]
Hello abdu292,

Having used this in a couple of small/medium-sized projects I haven't had any noticeable performance issues in regards to fetching entities from store. Fetch operations within the default data repository implementation are done without EF tracking, and mapping using Automapper is generally quite fast, especially in the latest version. Plus you can implement your own mapping logic if you find that Automapper is not sufficient.

I'll work on posting a few metrics once time permits, just to have a reference on the performance of this.

**Comment by abdu292** [comment]
That would be great. Thanks a lot @thecodewrapper!
